cfn_stack: cloud-resume-challenge
aws_region: us-east-1

aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID_HERE
aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY_HERE

bucket_name: your-unique-cloud-resume-bucket-name
