AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud Resume Challenge - S3 Website + CloudFront + Redirect (www -> apex) (DNS + ACM managed outside CFN)

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for the Cloud Resume frontend (also your apex domain)

  DomainName:
    Type: String
    Description: Apex domain (e.g., cloudwithzarapalevani.online)

  AcmCertificateArn:
    Type: String
    Description: "ACM certificate ARN in us-east-1 that covers DomainName and www.DomainName"

Resources:
  ResumeBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  ResumeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ResumeBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

  WwwToApexFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "${AWS::StackName}-www-to-apex"
      AutoPublish: true
      FunctionConfig:
        Comment: Redirect www to apex
        Runtime: cloudfront-js-1.0
      FunctionCode: !Sub |
        function handler(event) {
          var req = event.request;
          var host = req.headers.host.value;

          if (host === "www.${DomainName}") {
            return {
              statusCode: 301,
              statusDescription: "Moved Permanently",
              headers: {
                location: { value: "https://${DomainName}" + req.uri }
              }
            };
          }
          return req;
        }

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Cloud Resume distribution for ${DomainName}"
        DefaultRootObject: index.html

        PriceClass: PriceClass_100
        HttpVersion: http2
        IPV6Enabled: true

        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"

        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        Origins:
          - Id: S3WebsiteOrigin
            DomainName: !Sub "${BucketName}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

        DefaultCacheBehavior:
          TargetOriginId: S3WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt WwwToApexFunction.FunctionARN

        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /error.html
            ErrorCachingMinTTL: 10
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error.html
            ErrorCachingMinTTL: 10

Outputs:
  WebsiteURL:
    Description: S3 static website endpoint (HTTP only)
    Value: !GetAtt ResumeBucket.WebsiteURL

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  HttpsURL:
    Description: Primary HTTPS URL for your site
    Value: !Sub "https://${DomainName}"
